routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ContactController;
use App\Http\Controllers\AboutController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\EventController;
use App\Http\Controllers\SubscriptionController;
use App\Http\Controllers\CommonController;
use App\Http\Controllers\CartController;
use App\Http\Controllers\OrderController;
use App\Models\Page;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(
    [
        'prefix' => LaravelLocalization::setLocale(),
        'middleware' => [ 'localeSessionRedirect', 'localizationRedirect', 'localeViewPath' ]
    ], function(){
    Route::get('/', [HomeController::class, 'index'])->name('index');
    Route::get('/contact-us', [ContactController::class, 'index'])->name('contact-us');
    Route::post('/contact/store', [ContactController::class, 'storeContact'])->name('contact.store');
    Route::get('/about-us', [AboutController::class, 'index'])->name('about-us');
    //Route::get('/how-to-use', [HomeController::class, 'howToUse'])->name('how-to-use');
    Route::redirect('/how-to-use', '/')->name('how-to-use');

    Auth::routes();

    Route::get('/home', [HomeController::class, 'index'])->name('home');

    Route::group(['middleware' => ['auth']], function () {
        Route::get('/profile', [UserController::class, 'index'])->name('profile');
        Route::get('/edit-profile', [UserController::class, 'edit'])->name('edit-profile');
        Route::post('/update-profile', [UserController::class, 'update'])->name('update-profile');
        Route::resource('order',OrderController::class);

    });

    Route::get('/events', [EventController::class, 'list'])->name('events.list');
    Route::any('/events/{slug}', [EventController::class, 'show'])->name('events.show');

    Route::get('/get-cities/{country_id}', [CommonController::class, 'getCities'])->name('getCities');
    Route::post('/subscribe', [SubscriptionController::class, 'subscribe'])->name('subscribe');

    Route::resource('cart',CartController::class);

    // Routes of dynamic pages
    if(\Illuminate\Support\Facades\Schema::hasTable('pages')) {
        foreach(Page::all() as $page){
            Route::view($page->getRawOriginal('url') , 'page' , compact('page'));
        }
    }
});

resources/views/about.blade.php
@extends('layouts.master')
@section('title')
    {{ __('about us') }}
@endsection
@section('style')
@endsection
@section('content')
    @include('layouts.banner',['class' => 'aboutusbg', 'title' => __('about us'), 'bannerImage' =>  $about->getFirstMedia() ])

    <section class="aboutsection">
        <div class="container">
            <div class="row">
                <div class="col-sm-3">
                    <div class="titleiconsec">

                        <div class="iconsize">
                            <i class="icon-calendar icons"></i>
                        </div>
                        <h5 class="tetleaboutsec">Create your event</h5>
                        <p class="paragaboutsec">It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.</p>
                    </div>
                    <div class="titleiconsec">
                        <div class="iconsize">
                            <i class="icon-star icons"></i>
                        </div>
                        <h5 class="tetleaboutsec">Choose your gifts</h5>
                        <p class="paragaboutsec">It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.</p>
                    </div>
                </div>
                <div class="col-sm-3">
                    <div class="titleiconsec">
                        <div class="iconsize">
                            <i class="icon-heart icons"></i>
                        </div>
                        <h5 class="tetleaboutsec">Start a card gift</h5>
                        <p class="paragaboutsec">It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.</p>
                    </div>

                    <div class="titleiconsec">

                        <div class="iconsize">
                            <i class="icon-user icons"></i>
                        </div>
                        <h5 class="tetleaboutsec">Buy gift for your friend</h5>
                        <p class="paragaboutsec">It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.</p>
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="jout">
                        <h2>Your journey into the world of gifts begins now</h2>
                        <p>
                            He brings you gifts that do not fit your needs, and you wish your friends and family would bring you other gifts?
                            When your friends celebrate and you wish to bring useful gifts for them?

                        </p>
                        <p>
                            We have given you the solution. With Gift Shop, you can now say about your occasion and write gifts that you wish your friends would bring. You can also see your friends' occasions and buy the appropriate gifts for them.

                        </p>

                        <a href="#" class="btn btn-danger startjourny">Create your event</a>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section class="aboutcardgift-2">
        <div class="container">
            <div class="row">
                <div class="col-sm-6">
                    <img src="{{ $about->getFirstMedia() ?? asset('img/aboutus.png') }}" class="img-responsive"/>
                </div>
                <div class="col-sm-6">
                    <h2>{{ $about->title }}</h2>
                    <p>{!! $about->content  !!}</p>
                </div>
            </div>
        </div>
    </section>

    <section class="world_service">
        <div class="container">
            <div class="world_service_inner">
                <div class="row">
                    <div class="col-lg-3">
                        <div class="world_service_item">
                            <h4><img src="{{ asset('img/icon/world-icon-1.png') }}" alt="">{{ __('Special Service') }}</h4>
                        </div>
                    </div>
                    <div class="col-lg-3">
                        <div class="world_service_item">
                            <h4><img src="{{ asset('img/icon/world-icon-2.png') }}" alt="">{{ __('247 Help Center') }}</h4>
                        </div>
                    </div>
                    <div class="col-lg-3">
                        <div class="world_service_item">
                            <h4><img src="{{ asset('img/icon/world-icon-3.png') }}" alt="">{{ __('Safe Payment') }}</h4>
                        </div>
                    </div>
                    <div class="col-lg-3">
                        <div class="world_service_item">
                            <h4><img src="{{ asset('img/icon/world-icon-4.png') }}" alt="">{{ __('Home Shopping') }}</h4>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

@endsection
@section('script')
@endsection

resources/views/cart.blade.php
@extends('layouts.master')
@section('title')
    {{ __('Cart') }}
@endsection
@section('style')
@endsection
@section('content')
    @include('layouts.banner',['class' => 'solid_banner_area loginbackground', 'title' => __('Start a card gift') ])

    <!--================Shopping Cart Area =================-->
    <section class="shopping_cart_area p_100">
        <div class="container">
            <form action="{{ route('order.store') }}" method="post" data-parsley-validate>
                @csrf
                <div class="row">
                    <div class="col-lg-8">
                        <div class="cart_items">
                            <h3>{{ __('Available gifts') }}</h3>
                            <div class="table-responsive-md">
                                <table class="table">
                                    <thead>
                                    <tr>
                                        <th scope="col"></th>
                                        <th scope="col">{{ __('Gift') }}</th>
                                        <th scope="col">{{ __('Qty') }}</th>
                                        <th scope="col">{{ __('Paid') }}</th>
                                        <th scope="col" style="width:100px;">{{ __('Share a gift') }}</th>
                                        <th scope="col">{{ __('Remaining') }}</th>
                                        <th>{{ __('Total') }}</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    @forelse($cartItems as $index => $item)
                                        <tr>
                                            <td>
                                                <a class="remove_item_btn" data-url="{{ route('cart.destroy',['cart' => $index]) }}" data-id="{{ $index }}" style="cursor:pointer;">
                                                    <img src="{{ asset('img/icon/close-icon.png') }}" title="{{ __('Remove') }}" alt="Remove">
                                                </a>
                                            </td>
                                            <td>
                                                <div class="media">
                                                    <div class="d-flex">
                                                        <img src="{{ $item['image'] }}" alt="Gift image" width="100">
                                                    </div>
                                                    <div class="media-body">
                                                        <h4>{{ $item['name'] }}</h4>
                                                    </div>
                                                </div>
                                            </td>
                                            <td><p>{{ $item['quantity'] }}</p></td>
                                            <td><p>{{ $item['paid'] }} {{ __('L.E') }}</p></td>
                                            <td>
                                                <input type="text" name="price[]" value="{{ $item['remaining'] }}" data-parsley-trigger="keyup"
                                                       data-parsley-type="digits"  placeholder="{{ $item['remaining'] }}" required data-parsley-min="1" data-parsley-max="{{ $item['remaining'] }}" class="form-control myshare">
                                                <input type="hidden" name="cartItemIndex[]" value="{{ $index }}">
                                            </td>
                                            <td><p>{{ $item['remaining'] }} {{ __('L.E') }}</p></td>
                                            <td><p>{{ $item['price'] }} {{ __('L.E') }}</p></td>
                                        </tr>
                                    @empty
                                        <strong style="position: relative;top: 115px;left: 315px;">No item added to cart yet</strong>
                                    @endforelse
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="cart_totals_area">
                            <h4>{{ __('Cart Totals') }}</h4>
                            <div class="cart_t_list">
                                <div class="media">
                                    <div class="d-flex">
                                        <h5>{{ __('My shared') }}</h5>
                                    </div>
                                    <div class="media-body">
                                        <h6>{{ cart()->total() }} {{ __('L.E') }}</h6>
                                    </div>
                                </div>
    {{--                                <div class="media">--}}
    {{--                                    <div class="d-flex">--}}
    {{--                                        <h5>{{ __('Description') }}</h5>--}}
    {{--                                    </div>--}}
    {{--                                    <div class="media-body">--}}
    {{--                                        <p>Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model tex</p>--}}
    {{--                                    </div>--}}
    {{--                                </div>--}}
                                <div class="media">
                                    <div class="d-flex">

                                    </div>
                                </div>
                            </div>
                            <div class="total_amount row m0 row_disable">
                                <div class="float-left">
                                    {{ __('Total') }}
                                </div>
                                <div class="float-right">
                                    {{ cart()->total() }} {{ __('L.E') }}
                                </div>
                            </div>
                        </div>
                        <button type="submit" class="btn subs_btn form-control" {{ count(cart()->items()) <= 0 ? 'disabled' : '' }}>{{ __('Proceed to checkout') }}</button>
                    </div>
                </div>
            </form>
        </div>
    </section>
    <!--================End Shopping Cart Area =================-->

@endsection
@section('script')
@endsection

resources/views/coming-events.blade.php
<div class="promotion_area">
    <div class="feature_inner row m0">
        <div class="left_promotion">
            <div class="f_add_item">
                <div class="f_add_img"><img class="img-fluid" src="img/feature-add/img-1.jpg" alt=""></div>
                <div class="f_add_hover">
                    <div class="sale">Comming</div>
                    <h4>Aya & Mohamed <br />Engagement</h4>
                    <a class="add_btn" href="#">View gifts<i class="arrow_right"></i></a>
                </div>
            </div>
        </div>
        <div class="right_promotion">
            <div class="f_add_item right_dir">
                <div class="f_add_img"><img class="img-fluid" src="img/feature-add/img-2.jpg" alt=""></div>
                <div class="f_add_hover">
                    <div class="off">Two days left</div>
                    <h4>Ramy<br />Birthday</h4>
                    <a class="add_btn" href="#">View gifts <i class="arrow_right"></i></a>
                </div>
            </div>
        </div>
    </div>
</div>

resources/views/contact.blade.php
@extends('layouts.master')
@section('title')
    {{ __('contact us') }}
@endsection
@section('style')
@endsection
@section('content')
    @include('layouts.banner',['class' => 'contactusbg', 'title' => __('contact us'), 'bannerImage' =>  $contact->getFirstMedia()])

    <!--================Contact Area =================-->
    <section class="contact_area p_100">
        <div class="container">
            <div class="contact_title">
                {!! $contact->contact ?? '' !!}
            </div>
            <div class="row contact_details">
                <div class="col-lg-4 col-md-6">
                    <div class="media">
                        <div class="d-flex">
                            <i class="fa fa-map-marker" aria-hidden="true"></i>
                        </div>
                        <div class="media-body">
                            {!! $contact->address !!}
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 col-md-6">
                    <div class="media">
                        <div class="d-flex">
                            <i class="fa fa-phone" aria-hidden="true"></i>
                        </div>
                        <div class="media-body">
                            <a href="tel:{{ $contact->phone_1 ?? '' }}">{{ $contact->phone_1 ?? '' }}</a>
                            <a href="tel:{{ $contact->phone_2 ?? '' }}">{{ $contact->phone_2 ?? '' }}</a>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 col-md-6">
                    <div class="media">
                        <div class="d-flex">
                            <i class="fa fa-envelope" aria-hidden="true"></i>
                        </div>
                        <div class="media-body">
                            <a href="mailto:{{ $contact->email_1 ?? '' }}">{{ $contact->email_1 ?? '' }}</a>
                            <a href="mailto:{{ $contact->email_2 ?? '' }}">{{ $contact->email_2 ?? '' }}</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="contact_form_inner">
                <h3>{{ __('Drop a Message') }}</h3>
                <form class="contact_us_form row" action="{{ route('contact.store') }}" method="post" id="contactForm" data-parsley-validate>
                    @csrf
                    <div class="form-group col-lg-4">
                        <input type="text" class="form-control @error('full_name') is-invalid @enderror" id="name" name="full_name" placeholder="{{ __('Full Name') }} *" value="{{ old('full_name') }}" required>
                        @error('full_name')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                    <div class="form-group col-lg-4">
                        <input type="email" class="form-control @error('email') is-invalid @enderror" id="email" name="email" placeholder="{{ __('Email Address') }} *" value="{{ old('email') }}" required>
                        @error('email')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                    <div class="form-group col-lg-4">
                        <input type="text" class="form-control @error('phone') is-invalid @enderror" id="phone" name="phone" data-parsley-type="digits" placeholder="{{ __('Phone') }}" value="{{ old('phone') }}" data-parsley-length="[11, 11]" required>
                        @error('phone')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                    <div class="form-group col-lg-12">
                        <textarea class="form-control @error('message') is-invalid @enderror" name="message" id="message" rows="1" placeholder="{{ __('Type Your Message') }}..." required>{{ old('message') }}</textarea>
                        @error('message')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                    <div class="form-group col-lg-12">
                        <button type="submit" value="{{ __('submit') }}" class="btn update_btn form-control">{{ __('Send Message') }}</button>
                    </div>
                </form>
            </div>
        </div>
    </section>
    <!--================End Contact Area =================-->
@endsection
@section('script')
@endsection

resources/views/home-about.blade.php
<section class="aboutcardgift">
    <div class="container">
        <div class="row">
            <div class="col-sm-4">
                <img src="{{ $about->image }}" class="img-responsive"/>
            </div>
            <div class="col-sm-8">
                <h2>{{ $about->title }}</h2>
                {!! $about->content !!}
            </div>
        </div>
    </div>
</section>

resources/views/home.blade.php
@extends('layouts.master')
@section('title')
    {{ __('home') }}
@endsection
@section('style')
@endsection
@section('content')
    <!--================Main Content Area =================-->
    <section class="home_sidebar_area">
        <div class="container">
            <div class="row row_disable">
                <div class="col-lg-9 float-md-right">
                    <div class="sidebar_main_content_area">

                        @include('search')

                        @include('slider')

                        @include('coming-events')

                        @include('home-about')

                        @include('latest-events')

                        @include('private-events')

                    </div>
                </div>

                @include('side-menu')

            </div>
        </div>
    </section>
    <!--================End Main Content Area =================-->

    <!--================World Wide Service Area =================-->
    @include('service')
    <!--================End World Wide Service Area =================-->
@endsection
@section('script')
@endsection

resources/views/latest-events.blade.php
<section class="fillter_latest_product">
    <div class="container">
        <div class="single_c_title">
            <h2>{{ __('Our Latest Events') }}</h2>
        </div>
        <div class="fillter_l_p_inner">
            <ul class="fillter_l_p">
                <li class="active" data-filter="*"><a href="#">{{ __('All') }}</a></li>
                @foreach($eventsCategories as $category)
                    <li data-filter=".{{ $category->id }}"><a href="#">{{ $category->name }}</a></li>
                @endforeach
            </ul>
            <div class="row isotope_l_p_inner">
                @foreach($events as $event)
                    <div class="col-lg-4 col-md-4 col-sm-6 {{ $event->category_id }}">
                        <div class="l_product_item">
                            <div class="l_p_img">
                                <a href="#">
                                    <img class="img-fluid" src="{{ $event->image }}" alt="Image">
                                    {{-- @if($gift->status == \App\Constants\Constants::DONE_STATUS)
                                        <h5 class="done">{{ __('Done') }}</h5>
                                    @endif --}}
                                </a>
                            </div>
                            <div class="l_p_text">
                                <ul>
                                    <!-- <li class="p_icon"><a href="#"><i class="icon_piechart"></i></a></li> -->
                                    <li><a class="add_cart_btn btn-danger" href="{{ route('events.show',['slug' => $event->slug]) }}">{{ __('View') }}</a></li>

                                    {{-- @if($gift->is_gift_card)
                                        <li><a class="add_card_btn" href="{{ route('cart.create',['gift_id' => $gift->id]) }}">{{ __('Make a card') }}</a></li>
                                    @endif --}}

                                    <!-- <li class="p_icon"><a href="#"><i class="icon_heart_alt"></i></a></li> -->
                                </ul>
                                <h4>{{ $event->name }}</h4>
                                {{-- <h5>{{ $gift->price }} {{ __('L.E') }}</h5> --}}
                            </div>
                        </div>
                    </div>
                @endforeach
            </div>
        </div>
    </div>
</section>

resources/views/page.blade.php
@extends('layouts.master')
@section('title')
    {{ $page->name ?? "" }}
@endsection
@section('style')
@endsection
@section('content')
    @include('layouts.banner',['class' => 'contactusbg', 'title' => $page->name, 'bannerImage' =>  $page->getFirstMedia() ])

    <section class="page-previewcss">
        <div class="container">
            <div class="row">
                <div class="col-sm-12">
                    <h2>{{ $page->name ?? "" }} </h2>
                    <p>{!! $page->details ?? "" !!}</p>
                </div>
            </div>

        </div>
    </section>

@endsection
@section('script')
@endsection

resources/views/private-events.blade.php
<div class="home_sidebar_blog">
    <h3 class="single_title privateevent">{{ __('private events') }}</h3>
    <p class="enterpassword">{{ __('you need to enter event password') }}</p>
    <div class="row">
        @forelse($privateEvents as $event)
            <div class="col-lg-3 col-sm-6">
                <div class="l_product_item">
                    <div class="l_p_img">
                        <img class="img-fluid" src="{{ $event->image }}" style="max-width: 100%;max-height: 318px;" alt="{{ $event->name }}">
                        <h5 class="sale"><i class="fa fa-lock"></i> {{ $event->category->name ?? "" }}</h5>
                    </div>
                    <div class="l_p_text">
                        <ul>
                            <li>
                                <form action="{{ route('events.show', ['slug' => $event->slug]) }}" method="post">
                                    @csrf
                                    <div class="input-group mb-3">
                                        <input class="form-control" type="password" name="password" required placeholder="{{ __('Enter event password') }}"/>
                                        <div class="input-group-prepend">
                                            <button class="btn btn-success" type="submit" style="cursor:pointer;">{{ __('Enter') }}</button>
                                        </div>
                                    </div>
                                </form>
                            </li>
                        </ul>
                        <h4>{{ $event->name ?? "" }}</h4>
                        <h5>{{ $event->date ?? "" }}</h5>
                    </div>
                </div>
            </div>
        @empty
        @endforelse
    </div>
</div>

resources/views/search.blade.php
<form action="{{ route('events.list') }}" method="get">
    <div class="advanced_search_area">
        <select class="selectpicker" name="category_id">
            <option selected disabled>{{ __('Search in events') }}</option>
            @foreach($eventsCategories as $category)
                <option value="{{ $category->id }}">{{ $category->name }}</option>
            @endforeach
        </select>
        <div class="input-group">
            <input type="text" name="key" class="form-control" placeholder="{{ __('Search') }}" >
            <span class="input-group-btn">
                <button class="btn btn-secondary" type="submit"><i class="icon-magnifier icons"></i></button>
            </span>
        </div>
    </div>
</form>

resources/views/service.blade.php
<section class="world_service">
    <div class="container">
        <div class="world_service_inner">
            <div class="row">
                <div class="col-lg-3">
                    <div class="world_service_item">
                        <h4><img src="{{ asset('img/icon/world-icon-1.png') }}" alt="Special Service">{{ __('Special Service') }}</h4>
                    </div>
                </div>
                <div class="col-lg-3">
                    <div class="world_service_item">
                        <h4><img src="{{ asset('img/icon/world-icon-2.png') }}" alt="247 Help Center">{{ __('247 Help Center') }}</h4>
                    </div>
                </div>
                <div class="col-lg-3">
                    <div class="world_service_item">
                        <h4><img src="{{ asset('img/icon/world-icon-3.png') }}" alt="Safe Payment">{{ __('Safe Payment') }}</h4>
                    </div>
                </div>
                <div class="col-lg-3">
                    <div class="world_service_item">
                        <h4><img src="{{ asset('img/icon/world-icon-4.png') }}" alt="Home Shopping">{{ __('Home Shopping') }}</h4>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

resources/views/test.blade.php
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
<form action="http://localhost:8000/test"  method="get">
    <input type="text" name="name" value="mustafa">
    <input type="submit" value="Submit">
</form>
</body>
</html>