routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ContactController;
use App\Http\Controllers\AboutController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\EventController;
use App\Http\Controllers\SubscriptionController;
use App\Http\Controllers\CommonController;
use App\Http\Controllers\CartController;
use App\Http\Controllers\OrderController;
use App\Models\Page;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(
    [
        'prefix' => LaravelLocalization::setLocale(),
        'middleware' => [ 'localeSessionRedirect', 'localizationRedirect', 'localeViewPath' ]
    ], function(){
    Route::get('/', [HomeController::class, 'index'])->name('index');
    Route::get('/contact-us', [ContactController::class, 'index'])->name('contact-us');
    Route::post('/contact/store', [ContactController::class, 'storeContact'])->name('contact.store');
    Route::get('/about-us', [AboutController::class, 'index'])->name('about-us');
    //Route::get('/how-to-use', [HomeController::class, 'howToUse'])->name('how-to-use');
    Route::redirect('/how-to-use', '/')->name('how-to-use');

    Auth::routes();

    Route::get('/home', [HomeController::class, 'index'])->name('home');

    Route::group(['middleware' => ['auth']], function () {
        Route::get('/profile', [UserController::class, 'index'])->name('profile');
        Route::get('/edit-profile', [UserController::class, 'edit'])->name('edit-profile');
        Route::post('/update-profile', [UserController::class, 'update'])->name('update-profile');
        Route::resource('order',OrderController::class);

    });

    Route::get('/events', [EventController::class, 'list'])->name('events.list');
    Route::any('/events/{slug}', [EventController::class, 'show'])->name('events.show');

    Route::get('/get-cities/{country_id}', [CommonController::class, 'getCities'])->name('getCities');
    Route::post('/subscribe', [SubscriptionController::class, 'subscribe'])->name('subscribe');

    Route::resource('cart',CartController::class);

    // Routes of dynamic pages
    if(\Illuminate\Support\Facades\Schema::hasTable('pages')) {
        foreach(Page::all() as $page){
            Route::view($page->getRawOriginal('url') , 'page' , compact('page'));
        }
    }
});

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav me-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ms-auto">
                        <!-- Authentication Links -->
                        @guest
                            @if (Route::has('login'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                                </li>
                            @endif

                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/layouts/banner.blade.php
<!--================Banner Area =================-->
<section class="solid_banner_area {{$class}}" style="background-image: url({{ $banner ?? asset('/img/banner/f-add-6.jpg') }}) !important;">
    <div class="container">
        <div class="solid_banner_inner">
            <h3>{{ $title }}</h3>
        </div>
    </div>
</section>
<!--================End Banner Area =================-->

resources/views/layouts/footer.blade.php
<footer class="footer_area">
    <div class="container">
        <div class="footer_widgets">
            <div class="row">
                <div class="col-lg-4 col-md-4 col-6">
                    <aside class="f_widget f_about_widget">
                        <img src="{{ asset('img/logo-1.png') }}" alt="" class="footerimage">
                        <p>{{ __('Now you can add your own occasion and choose the gifts that you like your friends to bring to you.') }}</p>
                        <ul>
                            <li><a href="{{ $contact->facebook ?? "/" }}" target="_blank"><i class="social_facebook"></i></a></li>
                            <li><a href="{{ $contact->twitter ?? "/" }}" target="_blank"><i class="social_twitter"></i></a></li>
                            <li><a href="{{ $contact->instagram ?? "/" }}" target="_blank"><i class="social_instagram"></i></a></li>
                            <li><a href="{{ $contact->youtube ?? "/" }}" target="_blank"><i class="social_youtube"></i></a></li>
                        </ul>
                    </aside>
                </div>
                <div class="col-lg-3 col-md-4 col-6">
                    <aside class="f_widget link_widget f_info_widget">
                        <div class="f_w_title">
                            <h3>{{ __('Information') }}</h3>
                        </div>
                        <ul>
                            <li><a href="{{ route('about-us') }}">{{ __('About') }}</a></li>
                            @if($pages)
                                @foreach($pages as $page)
                                    @if(in_array($page->position, [\App\Models\Page::FOOTER_POSITION, \App\Models\Page::BOTH_POSITION]))
                                        <li><a href="{{ $page->url }}">{{ ltrim($page->name) }}</a></li>
                                    @endif
                                @endforeach
                            @endif
                        </ul>
                    </aside>
                </div>
                <div class="col-lg-3 col-md-4 col-6">
                    <aside class="f_widget link_widget f_service_widget">
                        <div class="f_w_title">
                            <h3>{{ __('Customer Service') }}</h3>
                        </div>
                        <ul>
                            <li><a href="#">{{ __('My account') }}</a></li>
                            <li><a href="#">{{ __('Newsletter') }}</a></li>
                            <li><a href="{{ route('contact-us') }}">{{ __('contact us') }}</a></li>
                        </ul>
                    </aside>
                </div>
                <div class="col-lg-2 col-md-4 col-6">
                    <aside class="f_widget link_widget f_extra_widget">
                        <div class="f_w_title">
                            <h3>{{ __('Extras') }}</h3>
                        </div>
                        <ul>
                            <li><a href="#">{{ __('Add your Events') }}</a></li>
                            <li><a href="#">{{ __('Start card gifts') }}</a></li>
                        </ul>
                    </aside>
                </div>
            </div>
        </div>
        <div class="footer_copyright">
            <h5>©  {{ __('All rights reserved') }} <i class="fa fa-heart-o" style="color: red; font-weight: bold" aria-hidden="true"></i> {{ __('by') }} <a href="https://ideasqr.com" target="_blank">IdeaSQR</a>
            </h5>
        </div>
    </div>
</footer>

resources/views/layouts/header.blade.php
<!--================Menu Area =================-->
<header class="shop_header_area carousel_menu_area">
    <div class="carousel_top_header black_top_header row m0">
        <div class="container">
            <div class="carousel_top_h_inner">
                <div class="float-md-left">
                    <div class="top_header_left">
                        <div class="selector">
                            <select class="language_drop" name="locale" id="locale" style="width:300px;">
                                @foreach(LaravelLocalization::getSupportedLocales() as $localeCode => $properties)
                                    <option value='{{ $localeCode }}' data-url="{{ LaravelLocalization::getLocalizedURL($localeCode, null, [], true) }}" data-image="{{ asset('img/icon/'.$localeCode.'.png') }}" data-imagecss="flag yt" data-title="{{ $properties['native'] }}" {{ app()->getLocale() == $localeCode ? 'selected' : '' }}>{{ $properties['native'] }}</option>
                                @endforeach
                            </select>
                        </div>

                    </div>
                </div>
                <div class="float-md-right">
                    <ul class="account_list">
                        <li><a href="@auth{{ route('order.index') }}@endauth @guest{{ route('login') }}@endguest">{{ __('My orders') }}</a></li>
                        <!-- <li><a href="#">Wish List (0)</a></li> -->
                        <li><a href="{{ route('cart.index') }}">{{ __('Shopping Cart') }}</a></li>
                        @auth
                            <li>
                                <a href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                                    {{ __('Logout') }}
                                </a>

                                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                    {{ csrf_field() }}
                                </form>
                            </li>
                        @endauth

                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="carousel_menu_inner">
        <div class="container">
            <nav class="navbar navbar-expand-lg navbar-light bg-light">
                <a class="navbar-brand" href="/"><img src="{{ asset('img/logo-1.png') }}" alt=""></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>

                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item active"><a class="nav-link" href="/">{{ __('home') }}</a></li>
                        <li class="nav-item"><a class="nav-link" href="{{ route('about-us') }}">{{ __('About') }}</a></li>
                        <li class="nav-item"><a class="nav-link" href="{{ route('how-to-use') }}">{{ __('how to use') }} </a></li>
                        <li class="nav-item dropdown submenu">
                            <a class="nav-link dropdown-toggle" href="{{ route('events.list', ['type' => \App\Models\Event::PUBLIC_EVENT]) }}" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                {{ __('events') }} <i class="fa fa-angle-down" aria-hidden="true"></i>
                            </a>
                            <ul class="dropdown-menu">
                                <li class="nav-item"><a class="nav-link" href="{{ route('events.list', ['type' => \App\Models\Event::PUBLIC_EVENT]) }}">{{ __('public events') }}</a></li>
                                <li class="nav-item"><a class="nav-link" href="{{ route('events.list', ['type' => \App\Models\Event::PRIVATE_EVENT]) }}">{{ __('private events') }}</a></li>
                            </ul>
                        </li>
                        <li class="nav-item"><a class="nav-link" href="{{ route('contact-us') }}">{{ __('contact us') }}</a></li>
                        @if($pages)
                            @foreach($pages as $page)
                                @if(in_array($page->position, [\App\Models\Page::HEADER_POSITION, \App\Models\Page::BOTH_POSITION]))
                                <li class="nav-item"><a class="nav-link" href="{{ $page->url }}">{{ ltrim($page->name) }}</a></li>
                                @endif
                           @endforeach
                        @endif
                    </ul>
                    <ul class="navbar-nav justify-content-end">
                        <li class="user_icon"><a href="@auth{{ route('profile') }}@endauth @guest{{ route('login') }}@endguest"><i class="icon-user icons"></i></a></li>
                        <li class="cart_cart"><a href="{{ route('cart.index') }}"><i class="icon-handbag icons"></i></a></li>
                    </ul>
                </div>
            </nav>
        </div>
    </div>
</header>
<!--================End Menu Area =================-->

resources/views/layouts/master.blade.php
<!doctype html>
<html lang="{{ app()->getLocale() | 'en' }}">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <meta name="csrf-token" content="{{ csrf_token() }}" />
        <link rel="icon" href="{{ asset('img/favicon.png') }}" type="image/x-icon" />
        <title>@yield('title', __('gift'))</title>
        @include('layouts.style')
    </head>
    <body class="home_sidebar">
        <div class="home_box">
            @include('layouts.header')
            @yield('content')
            @include('layouts.footer')
        </div>
        @include('layouts.modals')
        @include('layouts.scripts')
        {!! Toastr::message() !!}
    </body>
</html>

resources/views/layouts/scripts.blade.php
<script src="{{ asset('assets/js/app.js') }}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/parsley.js/2.9.2/parsley.min.js" integrity="sha512-eyHL1atYNycXNXZMDndxrDhNAegH2BDWt1TmkXJPoGf1WLlNYt08CSjkqF5lnCRmdm3IrkHid8s2jOUY4NIZVQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="http://cdn.bootcss.com/toastr.js/latest/js/toastr.min.js"></script>
<script src="https:////cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
@yield('script')

resources/views/layouts/style.blade.php
<link href="{{ asset('assets/css/app.css') }}" rel="stylesheet" type="text/css"/>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<link rel="stylesheet" href="http://cdn.bootcss.com/toastr.js/latest/css/toastr.min.css">
<link rel="stylesheet" href="https:////cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css">
<style>
    .cart_cart a:before {
        content: "{{ count(cart()->items()) }}";
    }
</style>
@yield('style')

@if(app()->getLocale() == 'ar')
    <link rel="stylesheet" href="{{ asset('assets/css/rtl.css') }}">
@endif

resources/views/layouts/validation-errors.blade.php
@if ($errors->any())
    <div class="alert alert-danger">
        <ul class="list-unstyled">
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif