routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ContactController;
use App\Http\Controllers\AboutController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\EventController;
use App\Http\Controllers\SubscriptionController;
use App\Http\Controllers\CommonController;
use App\Http\Controllers\CartController;
use App\Http\Controllers\OrderController;
use App\Models\Page;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(
    [
        'prefix' => LaravelLocalization::setLocale(),
        'middleware' => [ 'localeSessionRedirect', 'localizationRedirect', 'localeViewPath' ]
    ], function(){
    Route::get('/', [HomeController::class, 'index'])->name('index');
    Route::get('/contact-us', [ContactController::class, 'index'])->name('contact-us');
    Route::post('/contact/store', [ContactController::class, 'storeContact'])->name('contact.store');
    Route::get('/about-us', [AboutController::class, 'index'])->name('about-us');
    //Route::get('/how-to-use', [HomeController::class, 'howToUse'])->name('how-to-use');
    Route::redirect('/how-to-use', '/')->name('how-to-use');

    Auth::routes();

    Route::get('/home', [HomeController::class, 'index'])->name('home');

    Route::group(['middleware' => ['auth']], function () {
        Route::get('/profile', [UserController::class, 'index'])->name('profile');
        Route::get('/edit-profile', [UserController::class, 'edit'])->name('edit-profile');
        Route::post('/update-profile', [UserController::class, 'update'])->name('update-profile');
        Route::resource('order',OrderController::class);

    });

    Route::get('/events', [EventController::class, 'list'])->name('events.list');
    Route::any('/events/{slug}', [EventController::class, 'show'])->name('events.show');

    Route::get('/get-cities/{country_id}', [CommonController::class, 'getCities'])->name('getCities');
    Route::post('/subscribe', [SubscriptionController::class, 'subscribe'])->name('subscribe');

    Route::resource('cart',CartController::class);

    // Routes of dynamic pages
    if(\Illuminate\Support\Facades\Schema::hasTable('pages')) {
        foreach(Page::all() as $page){
            Route::view($page->getRawOriginal('url') , 'page' , compact('page'));
        }
    }
});

app/Models/Event.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Spatie\MediaLibrary\HasMedia;
use Spatie\MediaLibrary\InteractsWithMedia;
use Cviebrock\EloquentSluggable\Sluggable;


class Event extends Model implements HasMedia
{
    use HasFactory, InteractsWithMedia, Sluggable;

    protected $fillable = ['name_en', 'name_ar', 'description_en', 'description_ar',
    'type', 'category_id', 'password', 'date', 'host_name', 'host_code', 'host_address',
        'host_country_id', 'host_city_id', 'slug', 'host_id'];

    const PUBLIC_EVENT = "public";
    const PRIVATE_EVENT = "private";
    const MediaCollectionName = 'image';

    protected $appends = ['image'];

    public function sluggable(): array
    {
        return [
            'slug' => [
                'source' => 'name_en'
            ]
        ];
    }

    public function getNameAttribute()
    {
        $currentLocal = 'name_'.app()->getLocale();
        return $this->$currentLocal;
    }

    public function getDescriptionAttribute()
    {
        $currentLocal = 'description_'.app()->getLocale();
        return $this->$currentLocal;
    }

    public function category()
    {
        return $this->belongsTo(Category::class,'category_id','id');
    }

    public function hostCountry()
    {
        return $this->belongsTo(Country::class,'host_country_id','id');
    }

    public function hostCity()
    {
        return $this->belongsTo(City::class,'host_city_id','id');
    }

    public function gifts()
    {
        return $this->hasMany(Gift::class);
    }

    public function getImageAttribute()
    {
        return $this->hasMedia(self::MediaCollectionName) ? $this->getFirstMediaUrl(self::MediaCollectionName) : asset(config('app.default_image'));
    }

    public function orderItems()
    {
        return $this->hasMany(OrderItem::class, 'event_id','id');
    }

    public function orders()
    {
        return $this->hasManyThrough(Order::class, OrderItem::class,'event_id','order_id','id','id');
    }

    public function host()
    {
        return $this->belongsTo(Host::class,'host_id','id');
    }
}

app/Http/Controllers/API/Dashboard/EventController.php
<?php

namespace App\Http\Controllers\API\Dashboard;

use App\Http\Controllers\Controller;
use App\Http\Requests\Dashboard\Admin\Event\StoreRequest;
use App\Http\Requests\Dashboard\Admin\Event\UpdateRequest;
use App\Http\Resources\EventResource;
use App\Http\Services\EventService;
use App\Http\Traits\ResponseTrait;
use Illuminate\Http\Response;
use Exception;

class EventController extends Controller
{
    use ResponseTrait;

    private $eventService;

    /**
     * Constructor
     *
     * @param EventService $eventService
     */
    public function __construct(EventService $eventService ) {
        $this->eventService = $eventService;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $events = $this->eventService->getEvents();
        return $this->success(null, Response::HTTP_OK, EventResource::collection($events));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreRequest $request)
    {
        $eventData = $request->validated();
        $event =  $this->eventService->createEvent($eventData);
        return $this->success(__('Event created successfully'), Response::HTTP_OK, EventResource::make($event));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Event  $event
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        try {
            $event = $this->eventService->findEvent($id);
            return $this->success(null, Response::HTTP_OK, EventResource::make($event));
        } catch (Exception $ex) {
            return $this->error($ex->getMessage() ,Response::HTTP_FORBIDDEN);
        }
    }


    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateRequest $request, $id)
    {
        try {
            $event = $this->eventService->update($request->validated(), $id);
            return $this->success(__('Event updated successfully'), Response::HTTP_OK, EventResource::make($event));
        } catch (Exception $ex) {
            return $this->error($ex->getMessage() ,Response::HTTP_FORBIDDEN);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int  $event
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try {
            $event = $this->eventService->delete($id);
            return $this->success(__('Event deleted successfully'), Response::HTTP_OK, $event);
        } catch (Exception $ex) {
            return $this->error($ex->getMessage() ,Response::HTTP_FORBIDDEN);
        }
    }
}

app/Http/Controllers/EventController.php
<?php

namespace App\Http\Controllers;

use App\Http\Services\EventService;
use App\Http\Services\SliderService;
use App\Http\Services\UserService;
use App\Models\Event;
use Brian2694\Toastr\Facades\Toastr;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\App;

class EventController extends Controller
{
    private $eventService;
    public function __construct(UserService $userService, EventService $eventService)
    {
        $this->eventService = $eventService;
    }

    public function list(Request $request)
    {
        $events = $this->eventService->getEvents($request->all(), true);
        $events->appends($request->all());
        $viewName = $request->has('type') ? ( $request->type == Event::PRIVATE_EVENT ? "event.private-events" : "event.public-events") : "event.events";

        return view($viewName, compact('events'));
    }

    public function show($slug, Request $request)
    {
        $event = $this->eventService->findEventBySlug($slug);
        if($event->type == Event::PRIVATE_EVENT){
            if(!$request->has('password') || $request->password != $event->password){
                Toastr::error(__('you need to enter event valid password'), __('error'));
                return redirect()->back();
            }
        }

        return view('event.view', compact('event'));
    }
}

resources/views/event/events.blade.php
@extends('layouts.master')
@section('title')
    {{ __('Events') }}
@endsection
@section('style')
@endsection
@section('content')
    @include('layouts.banner',['class' => 'eventsbackground', 'title' => __('All events'), 'bannerImage' =>  asset('img/banner/f-add-6.jpg') ])

    <!--================events Product Area =================-->
    <section class="categories_product_main p_80">
        <div class="container">
            <div class="categories_main_inner">
                <div class="row row_disable">
                    <div class="col-lg-9 float-md-right">
                        <div class="c_product_grid_details">

                            @forelse($events as $event)
                                <div class="c_product_item">
                                    <div class="row">
                                        <div class="col-lg-4 col-md-6">
                                            <div class="c_product_img">
                                                <img class="img-fluid" src="{{ $event->image }}" style="max-width: 268px;max-height: 318px;" alt="{{ $event->name }}">
                                            </div>
                                        </div>
                                        <div class="col-lg-8 col-md-6">
                                            <div class="c_product_text">
                                                @if($event->type == \App\Models\Event::PRIVATE_EVENT)
                                                    <ul>
                                                    <li>
                                                        <form action="{{ route('events.show', ['slug' => $event->slug]) }}" method="post">
                                                            @csrf
                                                            <div class="input-group mb-3">
                                                                <input class="form-control" type="password" name="password" required placeholder="{{ __('Enter event password') }}"/>
                                                                <div class="input-group-prepend">
                                                                    <button class="btn btn-success" type="submit" style="cursor:pointer;">{{ __('Enter') }}</button>
                                                                </div>
                                                            </div>
                                                        </form>
                                                    </li>
                                                </ul>
                                                @endif
                                                <h5>{{ $event->name ?? "" }}</h5>
                                                <h6>{{ __('Event date') }} <span>{{ $event->date ?? "" }}</span></h6>
                                                <p>
                                                    {!! $event->description ?? "" !!}
                                                </p>
                                                <ul class="c_product_btn">
                                                    @if($event->type == \App\Models\Event::PUBLIC_EVENT)
                                                        <li><a class="add_card_btn" href="{{ route('events.show', ['slug' => $event->slug]) }}">{{ __('View') }}</a></li>
                                                    @endif
                                                </ul>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            @empty
                                <h4 style="margin: auto;; font-weight: bolder; text-align: center">{{ __('No events yet') }}</h4>
                            @endforelse

                            @if($events)
                                <nav aria-label="Page navigation example" class="pagination_area">
                                    <ul class="pagination">
                                        @for($i = 1 ; $i <= $events->lastPage(); $i++)
                                            <li class="page-item"><a class="page-link" href="{{ $events->url($i) }}">{{ $i }}</a></li>
                                        @endfor
                                        @if($events->hasMorePages())
                                            <li class="page-item next"><a class="page-link" href="{{ $events->nextPageUrl() }}"><i class="fa fa-angle-right" aria-hidden="true"></i></a></li>
                                        @endif
                                    </ul>
                                </nav>
                            @endif
                        </div>
                    </div>
                    <div class="col-lg-3 float-md-right">
                        <div class="categories_sidebar">
                            @if(count($latestEvents) > 0)
                                <aside class="l_widgest l_p_categories_widget">
                                <div class="l_w_title">
                                    <h3>{{ __('latest events') }}</h3>
                                </div>
                                <ul class="navbar-nav">
                                    @foreach($latestEvents as $event)
                                        <li class="nav-item">
                                            <a class="nav-link" href="#">
                                                {{ $event->name ?? "" }}
                                            </a>
                                        </li>
                                    @endforeach
                                </ul>
                            </aside>
                            @endif
                            @if(count($completedGifts) > 0)
                                <aside class="l_widgest l_feature_widget">
                                <div class="l_w_title">
                                    <h3>{{ __('Completed Gifts') }}</h3>
                                </div>

                                @foreach($completedGifts as $completeGift)
                                    <div class="media">
                                        <div class="d-flex">
                                                <img src="{{ $completeGift->image }}" style="max-width: 100px;max-height: 70px;" alt="{{ $completeGift->name }}">
                                        </div>
                                        <div class="media-body">
                                            <h4>{{ $completeGift->name ?? "" }}</h4>
                                            <h5>{{ $completeGift->price ?? "" }}</h5>
                                        </div>
                                    </div>
                                @endforeach

                            </aside>
                            @endif
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!--================End events Product Area =================-->
@endsection
@section('script')
@endsection

resources/views/event/private-events.blade.php
@extends('layouts.master')
@section('title')
    {{ __('private events') }}
@endsection
@section('style')
@endsection
@section('content')
    @include('layouts.banner',['class' => 'eventsbackground', 'title' => __('All private events'), 'bannerImage' =>  asset('img/banner/f-add-6.jpg') ])

    <!--================events Product Area =================-->
    <section class="no_sidebar_2column_area">
        <div class="container">
            <div class="two_column_product">
                <div class="row">
                    @forelse($events as $event)
                        <div class="col-lg-3 col-sm-6">
                        <div class="l_product_item">
                            <div class="l_p_img">
                                <img class="img-fluid" src="{{ $event->getFirstMedia() ?? asset('img/product/birthday.jpg') }}" style="max-width: 268px;max-height: 318px;" alt="{{ $event->name }}">
                                <h5 class="sale"><i class="fa fa-lock"></i> {{ $event->category->name ?? "" }}</h5>
                            </div>
                            <div class="l_p_text">
                                <ul>
                                    <li>
                                        <form action="{{ route('events.show', ['slug' => $event->slug]) }}" method="post">
                                            @csrf
                                            <div class="input-group mb-3">
                                                <input class="form-control" type="password" name="password" required placeholder="{{ __('Enter event password') }}"/>
                                                <div class="input-group-prepend">
                                                    <button class="btn btn-success" type="submit" style="cursor:pointer;">{{ __('Enter') }}</button>
                                                </div>
                                            </div>
                                        </form>
                                    </li>
                                </ul>
                                <h4>{{ $event->name ?? "" }}</h4>
                                <h5>{{ $event->date ?? "" }}</h5>
                            </div>
                        </div>
                    </div>
                    @empty
                        <h4 style="margin: auto;; font-weight: bolder">{{ __('No events yet') }}</h4>
                    @endforelse
                </div>

                @if(count($events) > 0)
                    <nav aria-label="Page navigation example" class="pagination_area">
                        <ul class="pagination">
                            @for($i = 1 ; $i <= $events->lastPage(); $i++)
                                <li class="page-item"><a class="page-link" href="{{ $events->url($i) }}">{{ $i }}</a></li>
                            @endfor
                            @if($events->hasMorePages())
                                <li class="page-item next"><a class="page-link" href="{{ $events->nextPageUrl() }}"><i class="fa fa-angle-right" aria-hidden="true"></i></a></li>
                            @endif
                        </ul>
                    </nav>
                @endif
            </div>
        </div>
    </section>
    <!--================End events Product Area =================-->
@endsection
@section('script')
@endsection

resources/views/event/public-events.blade.php
@extends('layouts.master')
@section('title')
    {{ __('public events') }}
@endsection
@section('style')
@endsection
@section('content')
    @include('layouts.banner',['class' => 'eventsbackground', 'title' => __('All public events'), 'bannerImage' =>  asset('img/banner/f-add-6.jpg') ])

    <!--================events Product Area =================-->
    <section class="categories_product_main p_80">
        <div class="container">
            <div class="categories_main_inner">
                <div class="row row_disable">
                    <div class="col-lg-9 float-md-right">
                        <div class="c_product_grid_details">

                            @forelse($events as $event)
                                <div class="c_product_item">
                                    <div class="row">
                                        <div class="col-lg-4 col-md-6">
                                            <div class="c_product_img">
                                                <img class="img-fluid" src="{{ $event->image }}" style="max-width: 268px;max-height: 318px;" alt="{{ $event->name }}">
                                            </div>
                                        </div>
                                        <div class="col-lg-8 col-md-6">
                                            <div class="c_product_text">
                                                <h5>{{ $event->name ?? "" }}</h5>
                                                <h6>{{ __('Event date') }} <span>{{ $event->date ?? "" }}</span></h6>
                                                <p>
                                                    {!! $event->description ?? "" !!}
                                                </p>
                                                <ul class="c_product_btn">
                                                    <li><a class="add_card_btn" href="{{ route('events.show', ['slug' => $event->slug]) }}">{{ __('View') }}</a></li>
                                                </ul>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            @empty
                                <h4 style="margin: auto;; font-weight: bolder">{{ __('No events yet') }}</h4>
                            @endforelse

                            @if($events)
                                <nav aria-label="Page navigation example" class="pagination_area">
                                    <ul class="pagination">
                                        @for($i = 1 ; $i <= $events->lastPage(); $i++)
                                            <li class="page-item"><a class="page-link" href="{{ $events->url($i) }}">{{ $i }}</a></li>
                                        @endfor
                                        @if($events->hasMorePages())
                                            <li class="page-item next"><a class="page-link" href="{{ $events->nextPageUrl() }}"><i class="fa fa-angle-right" aria-hidden="true"></i></a></li>
                                        @endif
                                    </ul>
                                </nav>
                            @endif
                        </div>
                    </div>
                    <div class="col-lg-3 float-md-right">
                        <div class="categories_sidebar">
                            @if(count($latestEvents) > 0)
                                <aside class="l_widgest l_p_categories_widget">
                                <div class="l_w_title">
                                    <h3>{{ __('latest events') }}</h3>
                                </div>
                                <ul class="navbar-nav">
                                    @foreach($latestEvents as $event)
                                        <li class="nav-item">
                                            <a class="nav-link" href="#">
                                                {{ $event->name ?? "" }}
                                            </a>
                                        </li>
                                    @endforeach
                                </ul>
                            </aside>
                            @endif
                            @if(count($completedGifts) > 0)
                                <aside class="l_widgest l_feature_widget">
                                <div class="l_w_title">
                                    <h3>{{ __('Completed Gifts') }}</h3>
                                </div>

                                @foreach($completedGifts as $completeGift)
                                    <div class="media">
                                        <div class="d-flex">
                                                <img src="{{ $completeGift->image }}" style="max-width: 100px;max-height: 70px;" alt="{{ $completeGift->name }}">
                                        </div>
                                        <div class="media-body">
                                            <h4>{{ $completeGift->name ?? "" }}</h4>
                                            <h5>{{ $completeGift->price ?? "" }}</h5>
                                        </div>
                                    </div>
                                @endforeach

                            </aside>
                            @endif
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!--================End events Product Area =================-->
@endsection
@section('script')
@endsection

resources/views/event/view.blade.php
@extends('layouts.master')
@section('title')
    {{ $event->name ?? __('event') }}
@endsection
@section('style')
@endsection
@section('content')
    @include('layouts.banner',['class' => 'eventbackground', 'title' => $event->name ?? "", 'bannerImage' =>  $event->getFirstMedia() ])

    <!--================Product Details Area =================-->
    <section class="product_details_area">
        <div class="container">
            <div class="row">
                <div class="col-lg-5">
                    <div class="product_details_slider">
                        <img src="{{ $event->getFirstMedia() ?? asset('img/product/birthday.jpg') }}" class="{{ $event->name ?? __('event') }}"/>
                    </div>
                </div>
                <div class="col-lg-7">
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="product_details_text">
                                <h3>{{ __('Welcome to our event') }}</h3>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-6">
                            <div class="product_details_text">
                                <h6>{{ __('Event date') }}: <span>{{ $event->date ?? "" }}</span></h6>
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="product_details_text">
                                <h6>{{ __('Host name') }}: <span>{{ $event->host_name ?? $event->host_code }}</span></h6>
                            </div>
                        </div>
                    </div>
                    <div class="product_details_text">
                        {!! $event->description ?? "" !!}
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!--================End Product Details Area =================-->
    <hr/>

    <!--================End Related Product Area =================-->
    <section class="related_product_area">
        <div class="container">
            <div class="related_product_inner">
                <h2 class="single_c_title giftstitle"><i class="fa fa-gift"></i> {{ __('The gifts I want') }}</h2>
                <div class="row">

                    @foreach($event->gifts as $gift)
                        <div class="col-lg-3 col-md-3 col-sm-6">
                            <div class="l_product_item">
                                <div class="l_p_img">
                                    <a href="#">
                                        <img class="img-fluid" src="{{ $gift->getFirstMedia() ?? asset('img/product/birthday.jpg') }}" alt="">
                                        <h5 class="done">{{ $gift->status == 0 ? 'Not available' : '' }}</h5>
                                    </a>
                                </div>
                                <div class="l_p_text">
                                    <ul>
                                        <li><a class="add_cart_btn" href="{{ route('cart.create',['gift_id' => $gift->id]) }}">{{ __('Buy Now') }}</a></li>
                                        <li><a class="add_card_btn" href="{{ route('cart.create',['gift_id' => $gift->id]) }}">{{ __('Make a card') }}</a></li>
                                    </ul>
                                    <h4>{{ $gift->name ?? "" }}</h4>
                                    <h5>{{ $gift->price }}</h5>
                                </div>
                            </div>
                        </div>
                    @endforeach

                </div>
            </div>
        </div>
    </section>
    <!--================End Related Product Area =================-->

@endsection
@section('script')
@endsection